### ISSUE TITLE
[BACK-END]  - Retrieve all the information needed for the file bubble chart

### ISSUE THREAD

**Issue by godDeveloppeur** [visevol/Cscope#102]
Description 

The information we would like to have would be a list of this type of object :

```typescript
export interface FileModified {
  filepath: string;
  nbFileCodeLines: number;
  nbAddCodeLines: number;
  nbDeleteCodeLines: number;
  nbCodeLinesModified: number;
  modifiedRateAddOrDelCodeLines: number;
}
```
I want an improvement to this one: https://github.com/visevol/Cscope/pull/55

NB: This must be included between the start and end dates.

**Comment by syw1-art** [comment]
> Description
> 
> The information we would like to have would be a list of this type of object :
> 
> ```ts
> export interface FileModified {
>   filepath: string;
>   nbFileCodeLines: number;
>   nbAddCodeLines: number;
>   nbDeleteCodeLines: number;
>   nbCodeLinesModified: number;
>   modifiedRateAddOrDelCodeLines: number;
> }
> ```
> 
> I want an improvement to this one: #55
> 
> NB: This must be included between the start and end dates.

Do we really need nbFileCodeLines? What is it used fot? I assume it's the total number of lines in the file.

@zergov I checked the code rq and it doesn't seem like we save the number of modified lines. We only save added and deleted lines?
![image](https://github.com/user-attachments/assets/73441287-6f7d-4519-a494-b6e46918ba2b)

Not sure how to proceed from here.

**Comment by godDeveloppeur** [comment]
@zergov  and  @syw1-art  We can do that : addition - deletions 

```typescript
export interface FileModified {
  filepath: string; 
  nbAddCodeLines: number; // additions
  nbDeleteCodeLines: number; // deletions
  nbCodeLinesModified: number; // (additions + deletions) this represent the bubble size because we want to represent the change
}
```

"modifiedRateAddOrDelCodeLines" I wanted to use it for the color by doing (additions - deletions) / number of lines of code in the file but we can make do with (additions - deletions)

**Comment by zergov** [comment]
> addition - deletions

I think we should just get the count of lines using Gitland, rather than doing it this way. If you try to do `(additions - deletions)`, you need to load all `source_file_changes` since the first commit. Otherwise, the sum won't add up to the real number of lines.
