### ISSUE TITLE
[Backend] Add a route to search a repository by remote url

### ISSUE THREAD

**Issue by zergov** [visevol/Cscope#11]
Users needs to be able to search a repository by an URL.
We need a route that will accept a repository URL, and:
1. Search for an existing repository in our database
2. If we don't have the repository in our database, we must check if that repository exists on the remote. 
3. If it exists, we should return a payload to the frontend so that it can make a second query that will create a record of that repository in our database. 

Example:
![sequence-search-request](https://github.com/user-attachments/assets/414e3454-4b7f-4e31-a85d-60cb456c1383)

**Comment by syw1-art** [comment]
Shouldn't the repo be automatically be created in repositories.db after fetching infos from GitHub?
Why bother making the client send a second query?

**Comment by zergov** [comment]
@syw1-art

That's because the first request is a GET request, and GET requests should only be used to request data. 

Indexing a repository should be an explicit action via a POST request. 

Technically, the client could just make a single POST request as well.

**Comment by syw1-art** [comment]
I would rather make a single post request to minimize the number of api calls then.
