### ISSUE TITLE
[Backend] Categorize source files

### ISSUE THREAD

**Issue by zergov** [visevol/Cscope#70]
We need to categorize source files in git repositories. 

As of writing this, I don't have a strong opinion on how we should do this. We should at least define a clear list of type of files. Example:
- source
- documentation
- test
- plain (.txt)
- configuration (.toml, .yml)
- assets (png, jpg)
- binary

We can start categorizing files very naively as a first step. I.E: Look at the extension and the file path. 

Whenever we create a new `SourceFile` model, we should tag it with its category. This is the most straight forward since the category of the file shouldn't change over time. It also allows us to filter source files by category.

**Comment by syw1-art** [comment]
add a column filetype to source_files so we can filter by that

focus on python and java projects
