### ISSUE TITLE
[FRONT-END] -  Retrieve data from the API for the file history motion chart across commits

### ISSUE THREAD

**Issue by godDeveloppeur** [visevol/Cscope#89]
Description 

Retrieve data from the API for the file history motion chart across commits

**Comment by zergov** [comment]
@godDeveloppeur c'est supposé etre quoi ca au juste?

**Comment by godDeveloppeur** [comment]
@zergov  C'est bon, elle a été faite. C'était pour la connection entre le graph du frontend et les données de l'api
